name: foodservice
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_database: ^10.2.5
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.9.1
  intl: any
  image_picker: ^1.0.5
  firebase_storage: ^11.7.7
  firebase_auth_platform_interface: ^7.0.9
  pin_code_fields: ^8.0.1
  flutter_hooks: ^0.20.5
  device_info_plus: ^10.1.1
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - asset/
    - lib/l10n/
